disabled_rules:
  - trailing_whitespace
  - line_length
  - file_length
  - type_body_length
  - function_body_length

opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_optional_boolean
  - empty_string
  - fatal_error_message
  - first_where
  - modifier_order
  - overridden_super_call
  - redundant_nil_coalescing
  - unneeded_parentheses_in_closure_argument

included:
  - Sources
  - Tests

excluded:
  - .build
  - DerivedData
  - Package.swift

reporter: "xcode"
